# Site settings
course_name: COMP3516 Data Analytics for IoT
course_description: "COMP3516 HKU course offerings portal"
course_semester: "Offerings Portal"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://comp3516-hku.github.io" # the base hostname & protocol for your site
repository: "comp3516-hku/comp3516-hku.github.io"

schoolname: "School of Computing and Data Science, The University of Hong Kong (HKU)"
schoolurl: "https://cds.hku.hk"
twitter_username: 

address: |
    The University of Hong Kong
    Pokfulam
    Hong Kong

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
google_analytics: G-DSQPC15V5E

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
# permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop', 'vendor', 'vendor/bundle', 'vendor/cache', 'vendor/gems', 'vendor/ruby', 'node_modules']

dateformat: "%m/%d/%Y"

future: true
