# Site settings
course_name: COMP3516 Data analytics for IoT
course_description: "COMP3516 HKU Data analytics for IoT"
course_semester: "Spring 2025"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://comp3516-hku.github.io/" # the base hostname & protocol for your site

schoolname: "School of Computing and Data Science, The University of Hong Kong (HKU)"
schoolurl: "https://cds.hku.hk"
twitter_username: 

address: |
    The University of Hong Kong
    Pokfulam
    Hong Kong

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
google_analytics: G-DSQPC15V5E

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
# permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    assignments:
        output: true
    tutorials:
        output: true
    lectures:
        output: true
    announcements:
        output: false
    labs:
        output: true


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
